### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by pintagon** [Rus501/TicTacToe#1]
Reading from top-down:

## displayController

https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L2
I'm guessing`para` refers to the `<p>` tag but that doesn't tell me what the variable represents. Something like `playerTurn` would be more informative.

https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L4
I didn't even know you could use an element id as an implied global variable name - I would highly discourage this pattern because it's confusing where the var comes from and breaks scoping. For example if I have another variable named `main` in the same function I'd likely shadow the global main.

https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L8
Because you're listening for click events from `main`, you're forced to handle different types of events. I'd suggest different listeners for restart and for the [gameboard](https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/index.html#L15) itself. This allows you to split your logic into smaller well-defined functions instead of shoving everything into the `onclick` handler for `main`. I believe this is a good opportunity to return early after handling the restart. You're having to rely on [more conditionals](https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L20) to decide if you're handling a game cell or a restart button which is confusing to reason about and could be avoided by splitting `restart` out.

https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L23-L24
The `target.className === 'cell'` check should be it's own `if` statement. None of your remaining code handles the case when `className` wouldn't be `cell` and it'd clear you up to use an `else` instead of `else if` [here](https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L32)

https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L41
Are the returned values actually used?

https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L42
I had to search for how `displayController` was being invoked. This isn't obvious at all - I'd personally just get rid of the function wrapping entirely and put it in the script directly. What you do want to wrap is the `onClick` function. I think the main reason you wanted `displayController` was so you could manipulate it from the game board, but more on that below.

## gameBoard

It's not clear who's actually driving the display of the gameboard because both the `gameBoard` and `displayController` are setting variables on each other. 

https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L54
I'd highly suggest changing this to return a boolean and having `displayController` actually drive the display. The only place you're calling `checkWinner` is from `displayController` anyways. It's confusing when the `gameBoard` breaks out of it's encapsulation as a game board and [touches](https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L73-L74) the `displayController`.

This way your outer most 'shell' / 'function' whatever is the `displayController` and your `gameBoard` is ONLY a game board which is controlled by displayController. Spaghetti happens when things control each other and makes it hard to trace logic vs. properly nesting each piece.

## random nit

Unless you're bundling your output, I wouldn't put normalize inside `node_modules`. Use something like a `public`/`static`/`assets` directory instead. It seems like you ran `npm install` on normalize but there's no `package.json`. Since you aren't bundling, I'd just use a CDN link listed on the [yarn page](https://classic.yarnpkg.com/en/package/normalize.css) page or add the CSS file yourself instead of using `npm install`

**Comment by Rus501** [comment]
> Reading from top-down:
> 
> ## displayController
> https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L2
> 
> 
> I'm guessing`para` refers to the `<p>` tag but that doesn't tell me what the variable represents. Something like `playerTurn` would be more informative.

Fixed
> https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L4
> 
> 
> I didn't even know you could use an element id as an implied global variable name - I would highly discourage this pattern because it's confusing where the var comes from and breaks scoping. For example if I have another variable named `main` in the same function I'd likely shadow the global main.

Yeah, tbh I did it right at the beginning and kinda forgot to change it late (fixed now)
> https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L8
> 
> 
> Because you're listening for click events from `main`, you're forced to handle different types of events. I'd suggest different listeners for restart and for the [gameboard](https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/index.html#L15) itself. This allows you to split your logic into smaller well-defined functions instead of shoving everything into the `onclick` handler for `main`. I believe this is a good opportunity to return early after handling the restart. You're having to rely on [more conditionals](https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L20) to decide if you're handling a game cell or a restart button which is confusing to reason about and could be avoided by splitting `restart` out.

Agreed, thx for noting it, it's just cuz I just learned event delegation and was tryna implement it, turns out it's not always the best solution
> https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L23-L24
> 
> 
> The `target.className === 'cell'` check should be it's own `if` statement. None of your remaining code handles the case when `className` wouldn't be `cell` and it'd clear you up to use an `else` instead of `else if` [here](https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L32)

Fixed (also tucked similar logic into a function)
> https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L41
> 
> 
> Are the returned values actually used?

They're not used, so I removed them
> https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L42
> 
> 
> I had to search for how `displayController` was being invoked. This isn't obvious at all - I'd personally just get rid of the function wrapping entirely and put it in the script directly. What you do want to wrap is the `onClick` function. I think the main reason you wanted `displayController` was so you could manipulate it from the game board, but more on that below.

It was an objective in TOP lesson, so I had to try to implement that
> ## gameBoard
> It's not clear who's actually driving the display of the gameboard because both the `gameBoard` and `displayController` are setting variables on each other.
> 
> https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L54
> 
> 
> I'd highly suggest changing this to return a boolean and having `displayController` actually drive the display. The only place you're calling `checkWinner` is from `displayController` anyways. It's confusing when the `gameBoard` breaks out of it's encapsulation as a game board and [touches](https://github.com/Rus501/TicTacToe/blob/fee991f93944c6716b0edb56d1cc5284ae3c29e8/main.js#L73-L74) the `displayController`.
> This way your outer most 'shell' / 'function' whatever is the `displayController` and your `gameBoard` is ONLY a game board which is controlled by displayController. Spaghetti happens when things control each other and makes it hard to trace logic vs. properly nesting each piece.

I was really overwhelmed and confused by the OOP concept and that's why I didn't know at first where to put all the variables, functions etc.
Thanks to your notes I think I got a hang of it and now code should look much more cleaner and understandable (imo at least)
> 
> ## random nit
> Unless you're bundling your output, I wouldn't put normalize inside `node_modules`. Use something like a `public`/`static`/`assets` directory instead. It seems like you ran `npm install` on normalize but there's no `package.json`. Since you aren't bundling, I'd just use a CDN link listed on the [yarn page](https://classic.yarnpkg.com/en/package/normalize.css) page or add the CSS file yourself instead of using `npm install`

That was my first experience with node modules so I obviously didn't really know what I was doing 😄 
Now should be fixed tho, linked the CDN normalize.css version

**Comment by pintagon** [comment]
https://github.com/Rus501/TicTacToe/blob/258e073875cad1406c781a93c8c4b2d5843b0758/main.js#L33-L36

Your previous code using `checkWinner` had the right idea, the issue was it did too much but now you've moved most of the logic into `makeTurn`. A better compromise is for the gameboard to still be responsible for calculating the winner like so:
``` javascript
const displayController = ()
const gameBoard = (() => {
	const gameboard = []
	const winner = null

	const clearGameboardArray = () => gameboard.length = 0

	const checkCondition = (n1, n2, n3, mark) => {
	   if (gameboard[n1] === mark && 
	   	 gameboard[n2] === mark && 
	   	 gameboard[n3] === mark) { gameBoard.winner = mark }
	}

        const isWinner = (mark) => {
           gameBoard.checkCondition(0, 1, 2, mark) 
           gameBoard.checkCondition(3, 4, 5, mark) 
           // .... etc.
        }

	return { gameboard, clearGameboardArray, checkCondition, winner }
})()
```

then within `makeTurn` you can call
``` js
  gameBoard.isWinner(player1.marker);
  gameBoard.isWinner(player2.marker);
```

I think your modules overall are a bit cleaner now - it's not always obvious how to separate things and you'll definitely get better at it over time! 

Quick note about your HTML - it'll be a good habit to start using the `<button>` tag instead of `<div>` on things the user can click on (aka the cells). It's a bit cleaner semantically and it allows you to use [`disabled`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) which is also semantically cleaner instead of adding your own `non_clickable` CSS class. The perceived functionality is the same, but for other devs reading your code it's easier to understand what you're trying to accomplish with the correct tags and the browser comes with builtin support for things like `disabled` so you dont have to reimplement them.

**Comment by Rus501** [comment]
Implemented suggested functionality
Big thanks for help!
